# Generated by Django 2.1.3 on 2018-11-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181112_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='app01.ClassList', verbose_name='已报班级'),
        ),
    ]
