# Generated by Django 2.1.3 on 2018-11-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20181120_1938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentstudyrecord',
            unique_together={('student', 'classstudyrecord')},
        ),
    ]
